baseURL = "https://waldeba.github.io/afromyth/"
languageCode = "en-us" 
title = "AFROMYTH"

[params]
  description = "Independent Homeware Brand | Handmade, reclaimed and worldwide decorative pieces."

[menu]
  [[menu.footer]]
    name = "HELP & FAQ"
    url = "/help-faq/"
    weight = 1
  [[menu.footer]]
    name = "ABOUT US" 
    url = "/about-us/"
    weight = 2
  [[menu.footer]]
    name = "CONTACT US"
    url = "/contact-us/"
    weight = 3
  [[menu.footer]]
    name = "TERMS & CONDITIONS"
    url = "/terms-and-conditions/"
    weight = 4
  [[menu.footer]]
    name = "PRIVACY POLICY"
    url = "/privacy-policy/"
    weight = 5